@startuml Uni3Uri1012
	title Uni3Uri1012
	start
	:ler(A);
	:ler(B);
	:ler(C);
	:tri = (A * C)/2;
	:pi = 3.14159;
	:circulo = pi * Math.pow(C, 2);
	:trapezio = ((A+B)* C)/2;
	:quadrado = Math.pow(B, 2);
	:retangulo = A*B;
	:escrever("TRIANGULO: " + tri);
	:escrever("CIRCULO: " + circulo);
	:escrever("TRAPEZIO: " + trapezio;
	:escrever("QUADRADO: " + quadrado);
	:escrever("RETANGULO: " + retangulo);
	stop
@enduml
