@startuml Uni3Uri1001
	title Uni3Uri1001
	start
		:ler(A);
		:ler(B);
		:X = A + B;
		:escrever("X = " + X);
	stop
@enduml

@startuml Uni3Uri1001_Classe
	class Uni3Uri1001 {
  	{static} +main(String[] args)
	}
@enduml
