@startuml Uni3Uri1019
	title Uni3Uri1019
	start
	:ler(tempo);
	:horas = tempo/3600;
	:minutos = (tempo%3600)/60;
	:segundos = (tempo%3600)%60;
	:escrever(horas + ":" + minutos + ":" + segundos);
	stop
@enduml
