@startuml Uni3Uri1008
	title Uni3Uri1008
	start
	:ler(numero);
	:ler(horas);
	:ler(valor);
	:salario = horas * valor;
	:escrever("NUMBER = " + numero);
	:escrever("SALARY = U$ " + salario);
	stop
@enduml
