@startuml Uni3Uri1018
	title Uni3Uri1018
	start
	:ler(valor);
	:n100 = (valor/100);
	:n50 = (valor%100)/50;
	:n20 = ((valor%100)%50)/20;
	:n10 = (((valor%100)%50)%20)/10;
	:n5 = ((((valor%100)%50)%20)%10)/5;
	:n2 = (((((valor%100)%50)%20)%10)%5)/2;
	:n1 = ((((((valor%100)%50)%20)%10)%5)%2)/1;
	:escrever(valor);
	:escrever(n100 + " nota(s) de R$ 100,00");
	:escrever(n50+ " nota(s) de R$ 50,00");
	:escrever(n20+ " nota(s) de R$ 20,00");
	:escrever(n10+ " nota(s) de R$ 10,00");
	:escrever(n5+ " nota(s) de R$ 5,00");
	:escrever(n2+ " nota(s) de R$ 2,00");
	:escrever(n1+ " nota(s) de R$ 1,00");
	stop
@enduml
